import { Typography, Box } from "@mui/material";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState, useEffect } from "react";
import DailyCardTable from "../components/DailyCardTable";
import Footer from "../components/Footer";
import SearchBar from "../components/SearchBar";
import type { MTGCard } from "../types";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeView />
    </>
  );
};

export default Home;

function HomeView() {
  const [mtg, setMtg] = useState<MTGCard[]>([]);

  useEffect(() => {
    console.log("It started");
    fetch("http://localhost:3009/api/item")
      .then((res) => res.json())
      .then((response) => {
        if (isObject(response) && "data" in response) {
          // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
          console.log("promise fulfilled", response.data);
          // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
          setMtg(response.data as MTGCard[]);
        }
      })
      .catch(console.error);
  }, []);

  return (
    <div>
      <Typography sx={{ mt: 1 }} variant="h1" color="#ff7961" align="center">
        Kokoelmani
      </Typography>
      <SearchBar />

      {/* <Banner /> */}
      <Typography sx={{ color: "green", mt: 6 }} variant="h4" align="center">
        Featured Highs of the Day
      </Typography>
      <Box
        sx={{
          display: "flex",
          justifyContent: "center",
          flexWrap: "wrap",
          "& > :not(style)": {
            m: 1,
            width: 340,
            height: 410,
            backgroundColor: "#efe4e2",
          },
        }}
      >
        <DailyCardTable />
        <DailyCardTable />
        <DailyCardTable />
        <DailyCardTable />
        <DailyCardTable />
      </Box>
      <Typography variant="h4" sx={{ color: "red", mt: 6 }} align="center">
        Featured Lows of the Day
      </Typography>
      <Box
        sx={{
          display: "flex",
          justifyContent: "center",
          flexWrap: "wrap",
          "& > :not(style)": {
            m: 1,
            width: 340,
            height: 410,
            backgroundColor: "#efe4e2",
          },
        }}
      >
        <DailyCardTable />
        <DailyCardTable />
        <DailyCardTable />
        <DailyCardTable />
        <DailyCardTable />
      </Box>

      <div>
        <Footer />
      </div>
    </div>
  );
}
function isObject(response: any) {
  return typeof response === "object" && !Array.isArray(response);
}
